; filepath: /home/martin/Osobni/Skola/CVUT/FEL-SIT/Bakalarska_prace/docker/php/custom-upload-settings.ini
upload_max_filesize = 100G
post_max_size = 100G ; Should be >= upload_max_filesize
; memory_limit = 512M ; Consider a reasonable memory_limit. 
; If your scripts don't load large files into memory, this doesn't need to be huge.
; max_execution_time = 3600 ; 1 hour, for very long uploads/processing
; max_input_time = 3600 ; 1 hour