services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./party-portal/apps/backend:/var/www/apps
    environment:
      APP_ENV: dev
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"


  auth:
    extends: php
    volumes:
      - ./party-portal/apps/backend/auth-service:/var/www/apps/auth
    working_dir: /var/www/apps/auth
    environment:
      XDEBUG_MODE: 'off'
      APP_ENV: dev
      DATABASE_URL: ${AUTH_URL}
      CHAT_SERVICE_ID: ${CHAT_SERVICE_ID}
      CHAT_SERVICE_SECRET: ${CHAT_SERVICE_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend-auth:
    build:
      context: ./party-portal/apps/frontend/auth
      dockerfile: ../../../../docker/node/Dockerfile
    volumes:
      - ./party-portal/apps/frontend/auth:/app
      - /app/node_modules
    networks:
      - backend
    environment:
      - VITE_API_URL=/auth/api


  chat:
    build:
      context: ./party-portal/apps/backend/chat-service
      dockerfile: ../../../../docker/node/chat.Dockerfile
    volumes:
      - ./party-portal/apps/backend/chat-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - AUTH_SERVICE_URL=http://nginx/auth
      - POSTGRES_USER=${CHAT_USER:-chat_user}
      - POSTGRES_PASSWORD=${CHAT_PASSWORD}
      - POSTGRES_DB=${CHAT_DB:-chat_db}
      - CHAT_SERVICE_ID=${CHAT_SERVICE_ID:-CHAT}
      - CHAT_SERVICE_SECRET=${CHAT_SERVICE_SECRET}
      - GENERAL_CHAT_NAME=General
      - DELETED_MESSAGE_TEXT='This message has been deleted'
    networks:
      - backend
    depends_on:
      - nginx
      - auth



  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./party-portal/apps/backend:/var/www/apps
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - auth
      - frontend-auth
    networks:
      - backend

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_ROOT_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_ROOT_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./databases/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./databases/auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./databases/auth-service/migrations:/docker-entrypoint-initdb.d/migrations
      - ./databases/auth-service/functions:/docker-entrypoint-initdb.d/functions
      - ./databases/auth-service/seeds:/docker-entrypoint-initdb.d/seeds
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ROOT_USER} -d ${POSTGRES_ROOT_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: