services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./party-portal/apps/backend:/var/www/apps
    environment:
      - APP_ENV=dev
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"


  auth:
    extends: php
    volumes:
      - ./party-portal/apps/backend/auth-service:/var/www/apps/auth
    working_dir: /var/www/apps/auth
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?serverVersion=17
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"


  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./party-portal/apps/backend:/var/www/apps
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - auth
    networks:
      - backend

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER:-auth_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-auth_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./databases/auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./databases/auth-service/migrations:/docker-entrypoint-initdb.d/migrations
      - ./databases/auth-service/functions:/docker-entrypoint-initdb.d/functions
      - ./databases/auth-service/seeds:/docker-entrypoint-initdb.d/seeds
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: