FROM node:20-alpine

WORKDIR /app

# Install dependencies only when needed
# COPY package.json package-lock.json ./
# RUN npm install

# Copy source
# COPY . .

# Expose Vite dev server port
# EXPOSE 5173
# EXPOSE 5174

# Start dev server
# CMD ["npm", "run", "dev", "--", "--host"]