<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250429072828 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE abilities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module VARCHAR(255) NOT NULL, resource VARCHAR(100) NOT NULL, resource_constraint TEXT DEFAULT NULL, action VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE login_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_address VARCHAR(45) NOT NULL, logged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, success BOOLEAN NOT NULL, failure_reason TEXT DEFAULT NULL, user_agent TEXT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_F16D9FFFA76ED395 ON login_log (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE role_abilities (expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, role_id INT NOT NULL, ability_id INT NOT NULL, PRIMARY KEY(role_id, ability_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_E9CC5E78D60322AC ON role_abilities (role_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_E9CC5E788016D8B2 ON role_abilities (ability_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_B63E2EC75E237E06 ON roles (name)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_abilities (expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, ability_id INT NOT NULL, PRIMARY KEY(user_id, ability_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_B8D80040A76ED395 ON user_abilities (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_B8D800408016D8B2 ON user_abilities (ability_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE user_roles (expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY(user_id, role_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_54FCD59FA76ED395 ON user_roles (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_54FCD59FD60322AC ON user_roles (role_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(100) NOT NULL, password_hash VARCHAR(60) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_1483A5E9F85E0677 ON users (username)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE login_log ADD CONSTRAINT FK_F16D9FFFA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE role_abilities ADD CONSTRAINT FK_E9CC5E78D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE role_abilities ADD CONSTRAINT FK_E9CC5E788016D8B2 FOREIGN KEY (ability_id) REFERENCES abilities (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_abilities ADD CONSTRAINT FK_B8D80040A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_abilities ADD CONSTRAINT FK_B8D800408016D8B2 FOREIGN KEY (ability_id) REFERENCES abilities (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FD60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE login_log DROP CONSTRAINT FK_F16D9FFFA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE role_abilities DROP CONSTRAINT FK_E9CC5E78D60322AC
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE role_abilities DROP CONSTRAINT FK_E9CC5E788016D8B2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_abilities DROP CONSTRAINT FK_B8D80040A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_abilities DROP CONSTRAINT FK_B8D800408016D8B2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FA76ED395
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FD60322AC
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE abilities
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE login_log
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE refresh_tokens
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE role_abilities
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE roles
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE user_abilities
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE user_roles
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE users
        SQL);
    }
}
