<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH6CV0i5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH6CV0i5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH6CV0i5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH6CV0i5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH6CV0i5\App_KernelDevDebugContainer([
    'container.build_hash' => 'H6CV0i5',
    'container.build_id' => '06a9a693',
    'container.build_time' => 1741343777,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH6CV0i5');
